go_import_path: github.com/spf13/viper

language: go

env:
  global:
    - GO111MODULE="on"
    - GOFLAGS="-mod=readonly"

go:
#  - 1.10.x
#  - 1.11.x
  - 1.12.x
#  - 1.13.x

os:
  - linux
  #- osx

#matrix:
#  allow_failures:
#    - go: tip
#  fast_finish: true

script:
  - go install ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...

after_success:
  - bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
